name: TypeScript Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

    #   - name: Install Dependencies
    #     run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Copy viewer
        run: cp -r viewer dist
